### ISSUE TITLE
How can i run this template

### ISSUE THREAD

**Issue by olufemioyedepo** [mrholek/CoreUI-AngularJS#10]
I've installed gulp via npm and I've also downloaded this template. How can I run it?

**Comment by xidedix** [comment]
hi @olufemioyedepo 
You are referencing [`AngularJS v1.6.x`](https://angularjs.org/) version on CoueUI. 
If it is right version for your needs, follow these steps:
```bash
cd AngularJS_Full_Project_GULP
npm install
gulp serve
```
see also: https://github.com/mrholek/CoreUI-AngularJS/blob/ef0c602aa489b3bf02885b04048f7203831b7730/AngularJS_Full_Project_GULP/package.json#L43-L47

**Comment by olufemioyedepo** [comment]
thanks. that solved the issue.

**Comment by xidedix** [comment]
@olufemioyedepo thanks for following up!

**Comment by olufemioyedepo** [comment]
You're welcome
